id: AAF9C9584
title: The Prayer which is the Source of All True Realization
type: translation
pechas:
- I991B081D
- IF589698B
- I47727D48
- I4085FBAB
- I9EE9832C
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:10:45.343847
  last_modified_at: 2023-01-04 13:10:45.343862
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I991B081D/C0E0: D7DB
  IF589698B/52FE: D7DB
  I47727D48/DA76: D7DB
  I4085FBAB/5D7C: D7DB
  I9EE9832C/3B5B: D7DB
